apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supertokens-ingress
spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{- include "supertokens.fullname" . | indent 1 }}
                port:
                  number: 3567